[package]
name = "egui_graphs"
version = "0.13.3"
authors = ["Dmitrii Samsonov <blitzarx1@gmail.com>"]
license = "MIT"
homepage = "https://github.com/blitzarx1/egui_graphs"
repository = "https://github.com/blitzarx1/egui_graphs"
description = "Interactive graph visualization widget for rust powered by egui"
edition = "2021"

[dependencies]
egui = "0.23"
rand = "0.8"
petgraph = "0.6"
crossbeam = "0.8"
serde = {version = "1.0", optional = true}

[features]
egui_persistence = ["dep:serde"]

[workspace]
members = ["examples/*"]
