[package]
name = "egui_graphs"
version = "0.0.11"
authors = ["Dmitrii Samsonov <blitzarx1@gmail.com>"]
license = "MIT"
homepage = "https://github.com/blitzarx1/egui_graphs"
repository = "https://github.com/blitzarx1/egui_graphs"
description = "Graph visualisation for egui"
edition = "2021"

[dependencies]
egui = "0.21.0"
petgraph = "0.6"

[workspace]
members = ["example"]
