[package]
name = "egui_graphs"
version = "0.0.19"
authors = ["Dmitrii Samsonov <blitzarx1@gmail.com>"]
license = "MIT"
homepage = "https://github.com/blitzarx1/egui_graphs"
repository = "https://github.com/blitzarx1/egui_graphs"
description = "Interactive graph visualization widget for rust powered by egui"
edition = "2021"

[dependencies]
egui = "0.21.0"

[workspace]
members = ["examples/*"]
