[package]
name = "egui_graphs"
version = "0.20.0"
authors = ["Dmitrii Samsonov <blitzar90@gmail.com>"]
license = "MIT"
homepage = "https://github.com/blitzarx1/egui_graphs"
repository = "https://github.com/blitzarx1/egui_graphs"
description = "Interactive graph visualization widget for rust powered by egui"
edition = "2021"

[dependencies]
egui = { version = "0.27", default-features = false }
rand = "0.8"
petgraph = { version = "0.6", default-features = false, features = [
  "stable_graph",
  "matrix_graph",
] }
crossbeam = { version = "0.8", optional = true }
serde = { version = "1.0", features = ["derive"], optional = true }
serde_json = { version = "1.0", optional = true }

[dev-dependencies]
eframe = "0.27.0"
fdg = { git = "https://github.com/grantshandy/fdg" }
bevy = "0.13"
bevy_egui = "0.27.0"
crossbeam = "0.8"

[features]
egui_persistence = ["dep:serde"]
events = ["dep:serde", "dep:serde_json", "dep:crossbeam"]
serde = ["dep:serde", "egui/serde", "petgraph/serde", "petgraph/serde-1"]
