[package]
name = "bevy_basic"
version = "0.1.0"
authors = ["Dmitrii Samsonov <blitzarx1@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
bevy = "0.13"
bevy_egui = "0.26.0"
egui_graphs = "0.19.0"
petgraph = "0.6"
