[package]
name = "demo"
version = "0.1.0"
authors = ["Dmitrii Samsonov <blitzarx1@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
egui_graphs = { path = "../..", features = ["events"] }
egui = "0.30"
eframe = "0.30"
serde_json = "1.0"
petgraph = "0.7"
# https://github.com/grantshandy/fdg/pull/25 applied
fdg = { git = "https://github.com/grantshandy/fdg", rev = "44f6c1bce649a67b5b19eb695b92e97a6e49cf2a" }
rand = "0.8"
crossbeam = "0.8"
