[package]
name = "basic"
version = "0.4.0"
authors = ["Dmitrii Samsonov <blitzarx1@gmail.com>"]
license = "MIT"
edition = "2021"

[dependencies]
egui_graphs = { path = "../../" }
egui = "0.21.0"
eframe = "0.21.3"
petgraph = "0.6.3"
